version: "3.9"
services:
  frontend:
    build: frontend
    ports:
      - "4200:4200"
      
  backend:
    build: backend

    ports:
      - "5000:5000"
    environment:
      - ENV MONGO_URI=mongodb+srv://Akshay:9eDFgdRgFoCIWNuL@cluster0.0zanqqt.mongodb.net/CampusKart?retryWrites=true&w=majority
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
   
